messages:
  prefix: '&7[&3ChestLock&7]'
  playerOnly: '&cOnly players can use this command.'
  playerNotFound: '&cPlayer not found.'
  checking: '&aYou can now check the list of players.'
  stoppedChecking: '&aYou have successfully stopped checking for players.'
  needTurningOff: '&aYou need to turn off %command% before using this command.'
  alreadyLocked: '&cThis chest is already locked.'
  locked: '&aSuccessfully locked chest.'
  unlocked: '&aSuccessfully unlocked chest.'
  memberOnlyLock: '&aOnly members or owners of this region can lock this chest.'
  ownerOnlyUnlock: '&cOnly the owner of this chest can unlock this chest.'
  notLocked: '&cThis chest is not locked.'
  checkFormat:
    - '&3Location: &b{x}, {y}, {z}'
    - '&3Owner: &b{owner}'
    - '&3Users: &b{users}'
  addedPlayer: '&aSuccessfully added {player}.'
  removedPlayer: '&aSuccessfully removed {player}.'
  onlyChest: '&cBlock is not a chest.'
  cantOpenChest: '&cYou cannot open this locked chest.'
  staffOpen: '&aOpened chest with staff perms...'
  playerNotMember: '&aThat player is not a member of this chest.'
  cannotOpenOp: '&cOPs cannot open locked chests.'
  cannotBreakOp: '&cOPs cannot break locked chests.'
