name: OmniChestLock
main: net.omni.chestlock.ChestLockPlugin
version: '1.0'
api-version: '1.15'
softdepend:
  - WorldGuard
  - WorldEdit
description: A plugin to chest locks. (WorldGuard support)
commands:
  lock:
    usage: /<command>
  unlock:
    usage: /<command>